#!/bin/bash

log () {
  echo "[$(date +'%F %T') | $(basename "$0")] $*"
}

requirements_path="${BASE_DIR}/${REQUIREMENTS_FILE}"
app_file_path="${BASE_DIR}/${MAIN_FILE}"
converted_python_file_name=".tinyapp_autogenerated"
converted_file_path="/home/${NB_USER}/${converted_python_file_name}.py"

IFS='' read -r -d '' variables <<EOF
Running with variables:
    requirements_path:   ${requirements_path}
    app_file_path:       ${app_file_path}
    converted_file_path: ${converted_file_path}
EOF
log "${variables}"

log "Working directory is ${BASE_DIR}"
cd ${BASE_DIR}

log "Installing user-listed dependencies ..."

# Enforce that app_file_path exist
[[ ! -f ${app_file_path} ]] && echo "${app_file_path} does not exist!" && exit 1

if [[ -f ${requirements_path} ]];
then
    log "${requirements_path} exists"
    while read requirement || [[ -n "${requirement}" ]]; do
        if [[ "${requirement}" != \#* ]] && [[ "${requirement}" = *[![:space:]]* ]]; then
            log "Installing ${requirement}"
            pip install ${requirement}
        fi
    done < "${requirements_path}"
    log "Done"
else
    log "${requirements_path} does not exist - continue"
fi

log "Converting main file to .py format ..."
jupyter-nbconvert "${app_file_path}" --to python --output "${converted_file_path}"

log "App is about to start"

if [[ "${TINY_APP_TYPE}" == "streamlit" ]];
then
    options_string="--server.port $STREAMLIT_PORT --server.baseUrlPath=${STREAMLIT_BASE_URL} --browser.gatherUsageStats false"
    log "Starting streamlit with options: ${options_string} ..."
    streamlit run "${converted_file_path}" ${options_string}
elif [[ "${TINY_APP_TYPE}" == "dash" ]];
then
    server_object="server"
    options_string="--threads 4 -b :$DASH_PORT"
    log "Starting dash with options: ${options_string} ..."
    gunicorn ${converted_python_file_name}:${server_object} ${options_string}
else
    log "Error: Unknown app type ${TINY_APP_TYPE}"
fi

exit 1
